spring:
  application:
    name: ai-interview
  datasource:
    url: jdbc:postgresql://localhost:5455/ai_interview
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000