spring:
  application:
    name: ai-interview
  datasource:
    url: jdbc:postgresql://localhost:5455/ai_interview
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openrouter/owl-alpha
          temperature: 0.7
springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
  file:
    upload-dir: ./uploads