server:
  port: 8181

spring:
  application:
    name: ai-interview
  datasource:
    url: jdbc:postgresql://localhost:5455/ai_interview
    username: postgres
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  ai:
    openai:
      api-key: sk***********************
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openrouter/owl-alpha
          temperature: 0.7
springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
  file:
    upload-dir: ./uploads
  tts:
    url: http://localhost:8801/v1/audio/speech
    model: tts-1
    voice: alloy
    enabled: true
